//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SilverApplesWebServiceConsole2.SilverApples {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ControllerSoap", Namespace="http://silverapples.com/")]
    public partial class Controller : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmplTablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMetaDataColumnNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllKeysOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllIndexesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTableConstraintsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTablesOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllTablesTwoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeeColumnsOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeeColumnsTwoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmplRelativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSick2004OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstNameTopSickOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateEmplContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmplContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmplContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmplContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Controller() {
            this.Url = global::SilverApplesWebServiceConsole2.Properties.Settings.Default.SilverApplesWebServiceConsole_SilverApples_Controller;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetEmployeesCompletedEventHandler GetEmployeesCompleted;
        
        /// <remarks/>
        public event GetEmplTablesCompletedEventHandler GetEmplTablesCompleted;
        
        /// <remarks/>
        public event GetAllInfoCompletedEventHandler GetAllInfoCompleted;
        
        /// <remarks/>
        public event GetMetaDataColumnNameCompletedEventHandler GetMetaDataColumnNameCompleted;
        
        /// <remarks/>
        public event GetAllKeysCompletedEventHandler GetAllKeysCompleted;
        
        /// <remarks/>
        public event GetAllIndexesCompletedEventHandler GetAllIndexesCompleted;
        
        /// <remarks/>
        public event GetAllTableConstraintsCompletedEventHandler GetAllTableConstraintsCompleted;
        
        /// <remarks/>
        public event GetAllTablesOneCompletedEventHandler GetAllTablesOneCompleted;
        
        /// <remarks/>
        public event GetAllTablesTwoCompletedEventHandler GetAllTablesTwoCompleted;
        
        /// <remarks/>
        public event GetAllEmployeeColumnsOneCompletedEventHandler GetAllEmployeeColumnsOneCompleted;
        
        /// <remarks/>
        public event GetAllEmployeeColumnsTwoCompletedEventHandler GetAllEmployeeColumnsTwoCompleted;
        
        /// <remarks/>
        public event GetEmplRelativesCompletedEventHandler GetEmplRelativesCompleted;
        
        /// <remarks/>
        public event GetSick2004CompletedEventHandler GetSick2004Completed;
        
        /// <remarks/>
        public event GetFirstNameTopSickCompletedEventHandler GetFirstNameTopSickCompleted;
        
        /// <remarks/>
        public event CreateEmplContractCompletedEventHandler CreateEmplContractCompleted;
        
        /// <remarks/>
        public event GetEmplContractCompletedEventHandler GetEmplContractCompleted;
        
        /// <remarks/>
        public event UpdateEmplContractCompletedEventHandler UpdateEmplContractCompleted;
        
        /// <remarks/>
        public event DeleteEmplContractCompletedEventHandler DeleteEmplContractCompleted;
        
        /// <remarks/>
        public event SearchCompletedEventHandler SearchCompleted;
        
        /// <remarks/>
        public event GetCustomerCompletedEventHandler GetCustomerCompleted;
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetEmployees", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmployees() {
            object[] results = this.Invoke("GetEmployees", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeesAsync() {
            this.GetEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void GetEmployeesAsync(object userState) {
            if ((this.GetEmployeesOperationCompleted == null)) {
                this.GetEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeesOperationCompleted);
            }
            this.InvokeAsync("GetEmployees", new object[0], this.GetEmployeesOperationCompleted, userState);
        }
        
        private void OnGetEmployeesOperationCompleted(object arg) {
            if ((this.GetEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeesCompleted(this, new GetEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetEmplTables", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmplTables() {
            object[] results = this.Invoke("GetEmplTables", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmplTablesAsync() {
            this.GetEmplTablesAsync(null);
        }
        
        /// <remarks/>
        public void GetEmplTablesAsync(object userState) {
            if ((this.GetEmplTablesOperationCompleted == null)) {
                this.GetEmplTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmplTablesOperationCompleted);
            }
            this.InvokeAsync("GetEmplTables", new object[0], this.GetEmplTablesOperationCompleted, userState);
        }
        
        private void OnGetEmplTablesOperationCompleted(object arg) {
            if ((this.GetEmplTablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmplTablesCompleted(this, new GetEmplTablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllInfo", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllInfo(string tablename) {
            object[] results = this.Invoke("GetAllInfo", new object[] {
                        tablename});
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllInfoAsync(string tablename) {
            this.GetAllInfoAsync(tablename, null);
        }
        
        /// <remarks/>
        public void GetAllInfoAsync(string tablename, object userState) {
            if ((this.GetAllInfoOperationCompleted == null)) {
                this.GetAllInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllInfo", new object[] {
                        tablename}, this.GetAllInfoOperationCompleted, userState);
        }
        
        private void OnGetAllInfoOperationCompleted(object arg) {
            if ((this.GetAllInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllInfoCompleted(this, new GetAllInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetMetaDataColumnName", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetMetaDataColumnName(string tablename) {
            object[] results = this.Invoke("GetMetaDataColumnName", new object[] {
                        tablename});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMetaDataColumnNameAsync(string tablename) {
            this.GetMetaDataColumnNameAsync(tablename, null);
        }
        
        /// <remarks/>
        public void GetMetaDataColumnNameAsync(string tablename, object userState) {
            if ((this.GetMetaDataColumnNameOperationCompleted == null)) {
                this.GetMetaDataColumnNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMetaDataColumnNameOperationCompleted);
            }
            this.InvokeAsync("GetMetaDataColumnName", new object[] {
                        tablename}, this.GetMetaDataColumnNameOperationCompleted, userState);
        }
        
        private void OnGetMetaDataColumnNameOperationCompleted(object arg) {
            if ((this.GetMetaDataColumnNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMetaDataColumnNameCompleted(this, new GetMetaDataColumnNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllKeys", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllKeys() {
            object[] results = this.Invoke("GetAllKeys", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllKeysAsync() {
            this.GetAllKeysAsync(null);
        }
        
        /// <remarks/>
        public void GetAllKeysAsync(object userState) {
            if ((this.GetAllKeysOperationCompleted == null)) {
                this.GetAllKeysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllKeysOperationCompleted);
            }
            this.InvokeAsync("GetAllKeys", new object[0], this.GetAllKeysOperationCompleted, userState);
        }
        
        private void OnGetAllKeysOperationCompleted(object arg) {
            if ((this.GetAllKeysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllKeysCompleted(this, new GetAllKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllIndexes", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllIndexes() {
            object[] results = this.Invoke("GetAllIndexes", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllIndexesAsync() {
            this.GetAllIndexesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllIndexesAsync(object userState) {
            if ((this.GetAllIndexesOperationCompleted == null)) {
                this.GetAllIndexesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllIndexesOperationCompleted);
            }
            this.InvokeAsync("GetAllIndexes", new object[0], this.GetAllIndexesOperationCompleted, userState);
        }
        
        private void OnGetAllIndexesOperationCompleted(object arg) {
            if ((this.GetAllIndexesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllIndexesCompleted(this, new GetAllIndexesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllTableConstraints", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllTableConstraints() {
            object[] results = this.Invoke("GetAllTableConstraints", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTableConstraintsAsync() {
            this.GetAllTableConstraintsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTableConstraintsAsync(object userState) {
            if ((this.GetAllTableConstraintsOperationCompleted == null)) {
                this.GetAllTableConstraintsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTableConstraintsOperationCompleted);
            }
            this.InvokeAsync("GetAllTableConstraints", new object[0], this.GetAllTableConstraintsOperationCompleted, userState);
        }
        
        private void OnGetAllTableConstraintsOperationCompleted(object arg) {
            if ((this.GetAllTableConstraintsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTableConstraintsCompleted(this, new GetAllTableConstraintsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllTablesOne", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllTablesOne() {
            object[] results = this.Invoke("GetAllTablesOne", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTablesOneAsync() {
            this.GetAllTablesOneAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTablesOneAsync(object userState) {
            if ((this.GetAllTablesOneOperationCompleted == null)) {
                this.GetAllTablesOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTablesOneOperationCompleted);
            }
            this.InvokeAsync("GetAllTablesOne", new object[0], this.GetAllTablesOneOperationCompleted, userState);
        }
        
        private void OnGetAllTablesOneOperationCompleted(object arg) {
            if ((this.GetAllTablesOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTablesOneCompleted(this, new GetAllTablesOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllTablesTwo", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllTablesTwo() {
            object[] results = this.Invoke("GetAllTablesTwo", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllTablesTwoAsync() {
            this.GetAllTablesTwoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllTablesTwoAsync(object userState) {
            if ((this.GetAllTablesTwoOperationCompleted == null)) {
                this.GetAllTablesTwoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllTablesTwoOperationCompleted);
            }
            this.InvokeAsync("GetAllTablesTwo", new object[0], this.GetAllTablesTwoOperationCompleted, userState);
        }
        
        private void OnGetAllTablesTwoOperationCompleted(object arg) {
            if ((this.GetAllTablesTwoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllTablesTwoCompleted(this, new GetAllTablesTwoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllEmployeeColumnsOne", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllEmployeeColumnsOne() {
            object[] results = this.Invoke("GetAllEmployeeColumnsOne", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeeColumnsOneAsync() {
            this.GetAllEmployeeColumnsOneAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeeColumnsOneAsync(object userState) {
            if ((this.GetAllEmployeeColumnsOneOperationCompleted == null)) {
                this.GetAllEmployeeColumnsOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeeColumnsOneOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployeeColumnsOne", new object[0], this.GetAllEmployeeColumnsOneOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeeColumnsOneOperationCompleted(object arg) {
            if ((this.GetAllEmployeeColumnsOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeeColumnsOneCompleted(this, new GetAllEmployeeColumnsOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetAllEmployeeColumnsTwo", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllEmployeeColumnsTwo() {
            object[] results = this.Invoke("GetAllEmployeeColumnsTwo", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeeColumnsTwoAsync() {
            this.GetAllEmployeeColumnsTwoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeeColumnsTwoAsync(object userState) {
            if ((this.GetAllEmployeeColumnsTwoOperationCompleted == null)) {
                this.GetAllEmployeeColumnsTwoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeeColumnsTwoOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployeeColumnsTwo", new object[0], this.GetAllEmployeeColumnsTwoOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeeColumnsTwoOperationCompleted(object arg) {
            if ((this.GetAllEmployeeColumnsTwoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeeColumnsTwoCompleted(this, new GetAllEmployeeColumnsTwoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetEmplRelatives", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmplRelatives(string no) {
            object[] results = this.Invoke("GetEmplRelatives", new object[] {
                        no});
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmplRelativesAsync(string no) {
            this.GetEmplRelativesAsync(no, null);
        }
        
        /// <remarks/>
        public void GetEmplRelativesAsync(string no, object userState) {
            if ((this.GetEmplRelativesOperationCompleted == null)) {
                this.GetEmplRelativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmplRelativesOperationCompleted);
            }
            this.InvokeAsync("GetEmplRelatives", new object[] {
                        no}, this.GetEmplRelativesOperationCompleted, userState);
        }
        
        private void OnGetEmplRelativesOperationCompleted(object arg) {
            if ((this.GetEmplRelativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmplRelativesCompleted(this, new GetEmplRelativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetSick2004", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetSick2004() {
            object[] results = this.Invoke("GetSick2004", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetSick2004Async() {
            this.GetSick2004Async(null);
        }
        
        /// <remarks/>
        public void GetSick2004Async(object userState) {
            if ((this.GetSick2004OperationCompleted == null)) {
                this.GetSick2004OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSick2004OperationCompleted);
            }
            this.InvokeAsync("GetSick2004", new object[0], this.GetSick2004OperationCompleted, userState);
        }
        
        private void OnGetSick2004OperationCompleted(object arg) {
            if ((this.GetSick2004Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSick2004Completed(this, new GetSick2004CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetFirstNameTopSick", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetFirstNameTopSick() {
            object[] results = this.Invoke("GetFirstNameTopSick", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstNameTopSickAsync() {
            this.GetFirstNameTopSickAsync(null);
        }
        
        /// <remarks/>
        public void GetFirstNameTopSickAsync(object userState) {
            if ((this.GetFirstNameTopSickOperationCompleted == null)) {
                this.GetFirstNameTopSickOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstNameTopSickOperationCompleted);
            }
            this.InvokeAsync("GetFirstNameTopSick", new object[0], this.GetFirstNameTopSickOperationCompleted, userState);
        }
        
        private void OnGetFirstNameTopSickOperationCompleted(object arg) {
            if ((this.GetFirstNameTopSickCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstNameTopSickCompleted(this, new GetFirstNameTopSickCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/CreateEmplContract", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateEmplContract(string code, string description) {
            this.Invoke("CreateEmplContract", new object[] {
                        code,
                        description});
        }
        
        /// <remarks/>
        public void CreateEmplContractAsync(string code, string description) {
            this.CreateEmplContractAsync(code, description, null);
        }
        
        /// <remarks/>
        public void CreateEmplContractAsync(string code, string description, object userState) {
            if ((this.CreateEmplContractOperationCompleted == null)) {
                this.CreateEmplContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEmplContractOperationCompleted);
            }
            this.InvokeAsync("CreateEmplContract", new object[] {
                        code,
                        description}, this.CreateEmplContractOperationCompleted, userState);
        }
        
        private void OnCreateEmplContractOperationCompleted(object arg) {
            if ((this.CreateEmplContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEmplContractCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetEmplContract", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetEmplContract(string code) {
            object[] results = this.Invoke("GetEmplContract", new object[] {
                        code});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmplContractAsync(string code) {
            this.GetEmplContractAsync(code, null);
        }
        
        /// <remarks/>
        public void GetEmplContractAsync(string code, object userState) {
            if ((this.GetEmplContractOperationCompleted == null)) {
                this.GetEmplContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmplContractOperationCompleted);
            }
            this.InvokeAsync("GetEmplContract", new object[] {
                        code}, this.GetEmplContractOperationCompleted, userState);
        }
        
        private void OnGetEmplContractOperationCompleted(object arg) {
            if ((this.GetEmplContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmplContractCompleted(this, new GetEmplContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/UpdateEmplContract", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateEmplContract(string code, string description) {
            this.Invoke("UpdateEmplContract", new object[] {
                        code,
                        description});
        }
        
        /// <remarks/>
        public void UpdateEmplContractAsync(string code, string description) {
            this.UpdateEmplContractAsync(code, description, null);
        }
        
        /// <remarks/>
        public void UpdateEmplContractAsync(string code, string description, object userState) {
            if ((this.UpdateEmplContractOperationCompleted == null)) {
                this.UpdateEmplContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmplContractOperationCompleted);
            }
            this.InvokeAsync("UpdateEmplContract", new object[] {
                        code,
                        description}, this.UpdateEmplContractOperationCompleted, userState);
        }
        
        private void OnUpdateEmplContractOperationCompleted(object arg) {
            if ((this.UpdateEmplContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmplContractCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/DeleteEmplContract", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteEmplContract(string code) {
            this.Invoke("DeleteEmplContract", new object[] {
                        code});
        }
        
        /// <remarks/>
        public void DeleteEmplContractAsync(string code) {
            this.DeleteEmplContractAsync(code, null);
        }
        
        /// <remarks/>
        public void DeleteEmplContractAsync(string code, object userState) {
            if ((this.DeleteEmplContractOperationCompleted == null)) {
                this.DeleteEmplContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmplContractOperationCompleted);
            }
            this.InvokeAsync("DeleteEmplContract", new object[] {
                        code}, this.DeleteEmplContractOperationCompleted, userState);
        }
        
        private void OnDeleteEmplContractOperationCompleted(object arg) {
            if ((this.DeleteEmplContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmplContractCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/Search", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Search(string fileName) {
            object[] results = this.Invoke("Search", new object[] {
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchAsync(string fileName) {
            this.SearchAsync(fileName, null);
        }
        
        /// <remarks/>
        public void SearchAsync(string fileName, object userState) {
            if ((this.SearchOperationCompleted == null)) {
                this.SearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchOperationCompleted);
            }
            this.InvokeAsync("Search", new object[] {
                        fileName}, this.SearchOperationCompleted, userState);
        }
        
        private void OnSearchOperationCompleted(object arg) {
            if ((this.SearchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCompleted(this, new SearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetCustomer", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetCustomer(string cPnr) {
            object[] results = this.Invoke("GetCustomer", new object[] {
                        cPnr});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerAsync(string cPnr) {
            this.GetCustomerAsync(cPnr, null);
        }
        
        /// <remarks/>
        public void GetCustomerAsync(string cPnr, object userState) {
            if ((this.GetCustomerOperationCompleted == null)) {
                this.GetCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerOperationCompleted);
            }
            this.InvokeAsync("GetCustomer", new object[] {
                        cPnr}, this.GetCustomerOperationCompleted, userState);
        }
        
        private void OnGetCustomerOperationCompleted(object arg) {
            if ((this.GetCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerCompleted(this, new GetCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://silverapples.com/GetCustomers", RequestNamespace="http://silverapples.com/", ResponseNamespace="http://silverapples.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCustomers() {
            object[] results = this.Invoke("GetCustomers", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[0], this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetEmployeesCompletedEventHandler(object sender, GetEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetEmplTablesCompletedEventHandler(object sender, GetEmplTablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmplTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmplTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllInfoCompletedEventHandler(object sender, GetAllInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetMetaDataColumnNameCompletedEventHandler(object sender, GetMetaDataColumnNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMetaDataColumnNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMetaDataColumnNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllKeysCompletedEventHandler(object sender, GetAllKeysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllKeysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllKeysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllIndexesCompletedEventHandler(object sender, GetAllIndexesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllIndexesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllIndexesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllTableConstraintsCompletedEventHandler(object sender, GetAllTableConstraintsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTableConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTableConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllTablesOneCompletedEventHandler(object sender, GetAllTablesOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTablesOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTablesOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllTablesTwoCompletedEventHandler(object sender, GetAllTablesTwoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllTablesTwoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllTablesTwoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllEmployeeColumnsOneCompletedEventHandler(object sender, GetAllEmployeeColumnsOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeeColumnsOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeeColumnsOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllEmployeeColumnsTwoCompletedEventHandler(object sender, GetAllEmployeeColumnsTwoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeeColumnsTwoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeeColumnsTwoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetEmplRelativesCompletedEventHandler(object sender, GetEmplRelativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmplRelativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmplRelativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetSick2004CompletedEventHandler(object sender, GetSick2004CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSick2004CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSick2004CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetFirstNameTopSickCompletedEventHandler(object sender, GetFirstNameTopSickCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstNameTopSickCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstNameTopSickCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreateEmplContractCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetEmplContractCompletedEventHandler(object sender, GetEmplContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmplContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmplContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateEmplContractCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DeleteEmplContractCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void SearchCompletedEventHandler(object sender, SearchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCustomerCompletedEventHandler(object sender, GetCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591